application: chatudacity
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
  
builtins:
- appstats: on

inbound_services:
- channel_presence

handlers:
- url: /.*
  secure: always
  script: main.app